/**
 * Multi-file HTML template snippets.
 *
 * Each template is an object mapping filename → content.
 * Single-file templates have one key; multi-file templates have several.
 */

var TEMPLATES = {

  blank: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Document</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n\n  <h1>Hello</h1>\n  <p>Start building here...</p>\n\n  <script src="script.js"><\/script>\n</body>\n</html>',
    'style.css': '/* Styles */\nbody {\n  font-family: system-ui, sans-serif;\n  margin: 2rem;\n}',
    'script.js': '// JavaScript\nconsole.log("Hello from script.js!");'
  },

  hello: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Hello World</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <h1>Hello, World! 🌍</h1>\n  <script src="script.js"><\/script>\n</body>\n</html>',
    'style.css': 'body {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n  margin: 0;\n  background: linear-gradient(135deg, #6366f1, #a855f7);\n  color: white;\n  font-family: system-ui, sans-serif;\n}\nh1 {\n  font-size: 3rem;\n  text-shadow: 0 2px 10px rgba(0,0,0,0.3);\n}',
    'script.js': 'console.log("Hello World loaded!");'
  },

  card: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Card Component</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="card">\n    <h2>🚀 Project Title</h2>\n    <p>A brief description of the project goes here. Keep it short and sweet.</p>\n    <button id="ctaBtn">Learn More</button>\n  </div>\n  <script src="script.js"><\/script>\n</body>\n</html>',
    'style.css': 'body {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n  margin: 0;\n  background: #0f172a;\n  font-family: system-ui, sans-serif;\n}\n.card {\n  background: #1e293b;\n  border-radius: 12px;\n  padding: 2rem;\n  max-width: 340px;\n  box-shadow: 0 8px 30px rgba(0,0,0,0.3);\n  color: #f1f5f9;\n}\n.card h2 { margin-bottom: 0.5rem; }\n.card p { color: #94a3b8; line-height: 1.6; margin-bottom: 1rem; }\n.card button {\n  background: #6366f1;\n  color: white;\n  border: none;\n  padding: 0.6rem 1.5rem;\n  border-radius: 6px;\n  cursor: pointer;\n  font-size: 0.9rem;\n}\n.card button:hover { background: #4f46e5; }',
    'script.js': 'document.getElementById("ctaBtn").addEventListener("click", function() {\n  alert("Thanks for clicking!");\n});\nconsole.log("Card component loaded.");'
  },

  form: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Basic Form</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="form-card">\n    <h2>Contact Us</h2>\n    <form id="contactForm">\n      <label for="name">Name</label>\n      <input type="text" id="name" placeholder="John Doe" required>\n\n      <label for="email">Email</label>\n      <input type="email" id="email" placeholder="you@example.com" required>\n\n      <label for="message">Message</label>\n      <textarea id="message" rows="4" placeholder="Your message..."></textarea>\n\n      <button type="submit">Send Message</button>\n    </form>\n  </div>\n  <script src="script.js"><\/script>\n</body>\n</html>',
    'style.css': 'body {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n  margin: 0;\n  background: #f1f5f9;\n  font-family: system-ui, sans-serif;\n}\n.form-card {\n  background: white;\n  padding: 2rem;\n  border-radius: 12px;\n  box-shadow: 0 4px 20px rgba(0,0,0,0.08);\n  width: 100%;\n  max-width: 400px;\n}\n.form-card h2 { margin-bottom: 1.2rem; }\nlabel {\n  display: block;\n  margin-bottom: 0.3rem;\n  font-size: 0.85rem;\n  font-weight: 500;\n  color: #334155;\n}\ninput, textarea {\n  width: 100%;\n  padding: 0.55rem 0.75rem;\n  margin-bottom: 1rem;\n  border: 1px solid #cbd5e1;\n  border-radius: 6px;\n  font-size: 0.9rem;\n  box-sizing: border-box;\n}\ninput:focus, textarea:focus {\n  outline: none;\n  border-color: #6366f1;\n  box-shadow: 0 0 0 3px rgba(99,102,241,0.15);\n}\nbutton[type="submit"] {\n  width: 100%;\n  padding: 0.65rem;\n  background: #6366f1;\n  color: white;\n  border: none;\n  border-radius: 6px;\n  font-size: 0.95rem;\n  cursor: pointer;\n}\nbutton[type="submit"]:hover { background: #4f46e5; }',
    'script.js': 'document.getElementById("contactForm").addEventListener("submit", function(e) {\n  e.preventDefault();\n  var name = document.getElementById("name").value;\n  console.log("Form submitted by: " + name);\n  alert("Thanks, " + name + "! Message sent.");\n});'
  },

  flexbox: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Flexbox Layout</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <header>\n    <strong>MyApp</strong>\n    <nav>\n      <a href="#">Home</a>\n      <a href="#">About</a>\n      <a href="#">Contact</a>\n    </nav>\n  </header>\n  <div class="main-content">\n    <aside>\n      <h3>Menu</h3>\n      <ul>\n        <li>📊 Dashboard</li>\n        <li>📁 Projects</li>\n        <li>⚙️ Settings</li>\n      </ul>\n    </aside>\n    <div class="content-area">\n      <h2>Dashboard</h2>\n      <div class="cards">\n        <div class="mini-card"><h4>Users</h4><p>1,234</p></div>\n        <div class="mini-card"><h4>Revenue</h4><p>$12,345</p></div>\n        <div class="mini-card"><h4>Orders</h4><p>567</p></div>\n      </div>\n    </div>\n  </div>\n  <footer>&copy; 2025 MyApp. All rights reserved.</footer>\n  <script src="script.js"><\/script>\n</body>\n</html>',
    'style.css': '* { margin: 0; padding: 0; box-sizing: border-box; }\nbody {\n  font-family: system-ui, sans-serif;\n  min-height: 100vh;\n  display: flex;\n  flex-direction: column;\n}\nheader {\n  background: #1e293b;\n  color: #f1f5f9;\n  padding: 1rem 2rem;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\nnav a { color: #94a3b8; text-decoration: none; margin-left: 1.5rem; }\nnav a:hover { color: #ffffff; }\n.main-content { flex: 1; display: flex; }\naside {\n  width: 220px;\n  background: #0f172a;\n  color: #94a3b8;\n  padding: 1.5rem;\n}\naside h3 { color: #f1f5f9; margin-bottom: 1rem; }\naside ul { list-style: none; }\naside li { padding: 0.4rem 0; cursor: pointer; }\naside li:hover { color: #ffffff; }\n.content-area {\n  flex: 1;\n  padding: 2rem;\n  background: #f8fafc;\n}\n.cards {\n  display: flex;\n  gap: 1rem;\n  flex-wrap: wrap;\n  margin-top: 1.5rem;\n}\n.mini-card {\n  background: white;\n  border: 1px solid #e2e8f0;\n  border-radius: 8px;\n  padding: 1.2rem;\n  flex: 1;\n  min-width: 180px;\n}\n.mini-card h4 { margin-bottom: 0.4rem; }\n.mini-card p { font-size: 0.85rem; color: #64748b; }\nfooter {\n  background: #1e293b;\n  color: #64748b;\n  text-align: center;\n  padding: 0.8rem;\n  font-size: 0.8rem;\n}',
    'script.js': 'console.log("Flexbox layout loaded.");\n\nvar cards = document.querySelectorAll(".mini-card");\ncards.forEach(function(card) {\n  card.addEventListener("click", function() {\n    console.log("Clicked: " + card.querySelector("h4").textContent);\n  });\n});'
  },

  multi: {
    'index.html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Multi-File Starter</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <header>\n    <h1>🚀 Multi-File Starter</h1>\n  </header>\n\n  <main>\n    <section class="hero">\n      <h2>Welcome</h2>\n      <p>This project has separate HTML, CSS, and JS files.</p>\n      <p>The preview automatically inlines your linked files!</p>\n      <button id="clickMe">Click Me</button>\n    </section>\n\n    <section class="features">\n      <div class="feature-card">\n        <span class="icon">📂</span>\n        <h3>Multi-File</h3>\n        <p>Edit HTML, CSS, and JS separately.</p>\n      </div>\n      <div class="feature-card">\n        <span class="icon">👁️</span>\n        <h3>Live Preview</h3>\n        <p>See changes instantly as you type.</p>\n      </div>\n      <div class="feature-card">\n        <span class="icon">🤖</span>\n        <h3>AI Powered</h3>\n        <p>Generate code with AI assistance.</p>\n      </div>\n    </section>\n  </main>\n\n  <footer>\n    <p>Built with HTML Code Preview</p>\n  </footer>\n\n  <script src="app.js"><\/script>\n</body>\n</html>',
    'style.css': '/* ===== Reset ===== */\n* { margin: 0; padding: 0; box-sizing: border-box; }\n\nbody {\n  font-family: system-ui, sans-serif;\n  background: #0f172a;\n  color: #f1f5f9;\n  min-height: 100vh;\n  display: flex;\n  flex-direction: column;\n}\n\n/* ===== Header ===== */\nheader {\n  text-align: center;\n  padding: 2rem;\n  background: linear-gradient(135deg, #6366f1, #a855f7);\n}\nheader h1 { font-size: 2rem; }\n\n/* ===== Main ===== */\nmain {\n  flex: 1;\n  padding: 2rem;\n  max-width: 900px;\n  margin: 0 auto;\n}\n\n.hero {\n  text-align: center;\n  padding: 3rem 1rem;\n}\n.hero h2 { font-size: 1.8rem; margin-bottom: 0.5rem; }\n.hero p { color: #94a3b8; margin-bottom: 1rem; }\n\n.hero button {\n  background: #6366f1;\n  color: white;\n  border: none;\n  padding: 0.75rem 2rem;\n  border-radius: 8px;\n  font-size: 1rem;\n  cursor: pointer;\n  transition: background 0.2s;\n}\n.hero button:hover { background: #4f46e5; }\n\n.features {\n  display: flex;\n  gap: 1rem;\n  flex-wrap: wrap;\n  margin-top: 2rem;\n}\n\n.feature-card {\n  background: #1e293b;\n  border-radius: 12px;\n  padding: 1.5rem;\n  flex: 1;\n  min-width: 200px;\n  text-align: center;\n  border: 1px solid #334155;\n}\n.feature-card .icon { font-size: 2rem; display: block; margin-bottom: 0.5rem; }\n.feature-card h3 { margin-bottom: 0.3rem; }\n.feature-card p { font-size: 0.85rem; color: #94a3b8; }\n\n/* ===== Footer ===== */\nfooter {\n  text-align: center;\n  padding: 1rem;\n  color: #64748b;\n  font-size: 0.8rem;\n  border-top: 1px solid #334155;\n}',
    'app.js': '// Main application script\n\nvar clickCount = 0;\n\ndocument.getElementById("clickMe").addEventListener("click", function() {\n  clickCount++;\n  console.log("Button clicked! Count: " + clickCount);\n  \n  var btn = this;\n  btn.textContent = "Clicked " + clickCount + " time" + (clickCount !== 1 ? "s" : "");\n  \n  // Briefly change color\n  btn.style.background = "#22c55e";\n  setTimeout(function() {\n    btn.style.background = "";\n  }, 300);\n});\n\nconsole.log("Multi-File Starter loaded!");'
  }

};

